spring.datasource.url=jdbc:postgresql://localhost:5432/mercearia_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
api.security.token.secret=z@fl4s_m3rc3ar1a_s3cr3t_k3y_2026