-- Add audit columns if they don't exist
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE categoria ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE categoria ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE produto ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE produto ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE pedido ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE pedido ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE item_pedido ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE item_pedido ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE imagem_carrossel ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE imagem_carrossel ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;